# Generated by Django 3.2.4 on 2021-06-04 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_game_tiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Sequence ordering for a specific game')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('col', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('action', models.CharField(choices=[('R', 'Reveal'), ('F', 'Flag')], default='R', help_text='Action being performed. "R" to reveal a tile, "F" to flag it.', max_length=1)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.game')),
            ],
            options={
                'ordering': ['game_id', 'order'],
                'unique_together': {('game_id', 'order')},
            },
        ),
    ]
