version: "3.9"

services:
  db:
    container_name: sweeper_postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    container_name: sweeper_django
    build: .
    command: uwsgi /code/uwsgi.ini
    volumes:
      - /var/www/static:/var/www/static
      - /var/log/sweeper:/var/log/sweeper
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
