version: "3.9"

services:
  db:
    container_name: sweeper_postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env_debug

  web:
    container_name: sweeper_django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - log_volume:/var/log/sweeper
    ports:
      - "8000:8000"
    env_file:
      - .env_debug
    depends_on:
      - db

volumes:
  log_volume: